# `NumPy`

* 数値計算をする上で重要な役割を果たすパッケージ。
* `numpy`は「ナンパイ」と読む。Numerical Pythonの略。
* 慣例として`np`としてインポートする。

In [5]:
import numpy as np

## `array`（配列）

### `1`次元配列

In [6]:
lst = [0, 10, 20, 30, 40, 50]

`np.array()`は１次元配列を作る。

In [7]:
arr = np.array(lst)
arr

array([ 0, 10, 20, 30, 40, 50])

### 要素の抽出

要素の位置の数え方はリストと同じ。
```
   0   1   2   3   4   5  （左から数える） 
 +---+---+---+---+---+---+
 | A | B | C | D | E | F |
 +---+---+---+---+---+---+
  -6  -5  -4  -3  -2  -1　（右から数える）
```

`arr`から`20`を取り出すには

In [8]:
arr[2]

20

**＜連続するデータの抽出＞**
連続する要素の抽出する（**スライシング**）場合を考えよう。
```
    [ start : end ]
```
* `start`：抽出する最初の要素のインデックス番号
* `end`：抽出する最後の要素の**次の**インデックス番号
* `:`の左を省略すると「最初から」という意味になる。
* `:`の右を省略すると「最後まで」という意味になる。

`arr`を`10`以降全てを抽出する場合：

In [9]:
arr[1:]

array([10, 20, 30, 40, 50])

`arr`の`50`以外を全てを抽出する場合：

In [11]:
arr[:4+1]

array([ 0, 10, 20, 30, 40])

もしくは

In [12]:
arr[:-1]

array([ 0, 10, 20, 30, 40])

## `array` vs `list`

次のリストのそれぞれの要素に`10`を足したいとしよう。

In [1]:
# CELL PROVIDED

lst0 = [1.0, 2.0, 3.0, 4.0, 5.0]

次のコードでは`10`を最後に追加し，リスト同士を結合するだけである。

In [2]:
lst0 + [10]

[1.0, 2.0, 3.0, 4.0, 5.0, 10]

より簡単なコードで実行できれば良いが，以下のコードではエラーが発生する。

In [3]:
# lst0 + 10

これを実現するのが`NumPy`の`array`である。

In [6]:
arr0 = np.array(lst0)
arr0

array([1., 2., 3., 4., 5.])

In [7]:
arr0 + 10

array([11., 12., 13., 14., 15.])

ベクトル演算（Vectorization）と呼ばれ、ループを使わずに個々の要素に直接働きかけ計算している。

In [8]:
arr0 - 5

array([-4., -3., -2., -1.,  0.])

In [9]:
arr0 * 10  

array([10., 20., 30., 40., 50.])

In [10]:
arr0 ** 2

array([ 1.,  4.,  9., 16., 25.])

In [11]:
np.sqrt(arr0)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [12]:
np.log(arr0)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

次の計算も可能である。

In [13]:
y = arr0 * 2 + np.sqrt(arr0) + 10
y

array([13.        , 15.41421356, 17.73205081, 20.        , 22.23606798])

## 様々な`NumPy`関数

**ルート $\left(\sqrt x\right)$**

In [45]:
np.sqrt(4)

2.0

**底が$e$の指数関数（$e^x$）**

In [46]:
np.exp(10)

22026.465794806718

**自然対数（$\log_ex$または$\ln x$）**

In [47]:
np.log(10)

2.302585092994046

**$a$から$b$までの区間を等間隔に割った$N$個の数字を返す。**
```
np.linspace(a,b,N)
```

In [50]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**標本平均**

`x`が数字の`array`やリストの場合

`np.mean(x)`$=\bar{x}=\dfrac{1}{n}\displaystyle\sum_{i=1}^{n}x_i$

In [13]:
# CELL PROVIDED

xx = [1,2,3,4,5,6]

In [14]:
np.mean(xx)

3.5

**標本分散**

`x`が数字の`array`やリストの場合

`np.var(x, ddof=0)`$=s_x^2=\dfrac{1}{1-\text{ddof}}\displaystyle\sum_{i=1}^n\left(x_i-\bar{x}\right)^2$（`ddof=0`がデフォルト）

In [1]:
np.var(xx, ddof=1)  # 標本不偏分散の場合は ddof=1

NameError: name 'np' is not defined

**標本標準偏差**

`x`が数字の`array`やリストの場合

`np.std(x, ddof=0)`$=s_x=\sqrt{s_x^2}$  （`ddof=0`がデフォルト）

In [20]:
np.std(xx, ddof=1)  # ddof=1としても不偏標準偏差とはならない

1.8708286933869707